import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { marked } from 'marked';
import { supabase } from '@/lib/supabaseClient';

export async function POST(req: Request) {
  try {
    const { reportId, doctorEmail, doctorName, reportMarkdown, patientName } = await req.json();

    if (!doctorEmail || !reportMarkdown) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
      }
    });

    // Use modern marked API
    const parsedMarkup = await marked.parse(reportMarkdown, { gfm: true, breaks: true } as any);
    const reportHTML = typeof parsedMarkup === 'string' ? parsedMarkup : reportMarkdown;

    await transporter.sendMail({
      from: `"PatientVoice" <${process.env.GMAIL_USER}>`,
      to: doctorEmail,
      subject: `PatientVoice Clinical Report — ${patientName}, ${new Date().toLocaleDateString()}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
          <div style="background: #0f172a; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
            <h1 style="margin:0; font-size: 20px;">🏥 PatientVoice Clinical Report</h1>
          </div>
          <div style="padding: 20px; border: 1px solid #e2e8f0; border-top: none;">
            <p>Dear Dr. ${doctorName},</p>
            <p>Your patient has shared an AI-assisted clinical symptom report via PatientVoice.</p>
            <hr/>
            <div style="background: #f8fafc; padding: 16px; border-radius: 6px; 
                        border-left: 4px solid #3b82f6;">
              ${reportHTML}
            </div>
            <hr/>
            <p style="font-size: 12px; color: #64748b;">
              ⚠️ This report is AI-generated for clinical communication purposes only 
              and does not constitute a medical diagnosis. Generated by PatientVoice.
            </p>
          </div>
        </div>
      `
    });

    return NextResponse.json({ success: true }, { status: 200 });

  } catch (err: any) {
    console.error('Email API Error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
